package com.ncu.mfc.mapper;

import com.ncu.mfc.dto.CnameAndTno;
import com.ncu.mfc.dto.GradeBtn;
import com.ncu.mfc.model.Degree;
import com.ncu.mfc.model.Grade;
import com.ncu.mfc.model.GradeKey;
import com.ncu.mfc.model.Level;

import java.util.List;

public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(GradeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated
     */
    int insertSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated
     */
    Grade selectByPrimaryKey(GradeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Grade record);

    List<Degree> selectDegree();

    Degree selectGraByCnoAndSno(GradeKey gradeKey);

    Level analyseAllGrade();

    Level analyseGrade(String cno);

    Level analyseGradeByTno(String tno);

    Level analyseGradeByTnoAndCname(CnameAndTno record);

    List<Degree> selectGraByTno(String tno);

    List<Degree> selectGraByTnoBtn(GradeBtn record);

    List<Degree> selectGraByStu(String sno);

    List<Degree> selectGraByStuBtn(GradeBtn record);
}