package com.ncu.mfc.mapper;

import com.ncu.mfc.model.TeachClassKey;

public interface TeachClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach_class
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TeachClassKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach_class
     *
     * @mbggenerated
     */
    int insert(TeachClassKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach_class
     *
     * @mbggenerated
     */
    int insertSelective(TeachClassKey record);
}