package com.ncu.mfc.mapper;

import com.ncu.mfc.model.teachClassKey;

public interface teachClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach_class
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(teachClassKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach_class
     *
     * @mbggenerated
     */
    int insert(teachClassKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teach_class
     *
     * @mbggenerated
     */
    int insertSelective(teachClassKey record);
}