package com.ncu.mfc.model;

public class GradeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.sno
     *
     * @mbggenerated
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.cno
     *
     * @mbggenerated
     */
    private String cno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.sno
     *
     * @return the value of grade.sno
     *
     * @mbggenerated
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.sno
     *
     * @param sno the value for grade.sno
     *
     * @mbggenerated
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.cno
     *
     * @return the value of grade.cno
     *
     * @mbggenerated
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.cno
     *
     * @param cno the value for grade.cno
     *
     * @mbggenerated
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }
}