package com.ncu.mfc.model;

public class teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tno
     *
     * @mbggenerated
     */
    private String tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tname
     *
     * @mbggenerated
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tsex
     *
     * @mbggenerated
     */
    private String tsex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tdepart
     *
     * @mbggenerated
     */
    private String tdepart;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tno
     *
     * @return the value of teacher.tno
     *
     * @mbggenerated
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tno
     *
     * @param tno the value for teacher.tno
     *
     * @mbggenerated
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tname
     *
     * @return the value of teacher.tname
     *
     * @mbggenerated
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tname
     *
     * @param tname the value for teacher.tname
     *
     * @mbggenerated
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tsex
     *
     * @return the value of teacher.tsex
     *
     * @mbggenerated
     */
    public String getTsex() {
        return tsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tsex
     *
     * @param tsex the value for teacher.tsex
     *
     * @mbggenerated
     */
    public void setTsex(String tsex) {
        this.tsex = tsex == null ? null : tsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tdepart
     *
     * @return the value of teacher.tdepart
     *
     * @mbggenerated
     */
    public String getTdepart() {
        return tdepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tdepart
     *
     * @param tdepart the value for teacher.tdepart
     *
     * @mbggenerated
     */
    public void setTdepart(String tdepart) {
        this.tdepart = tdepart == null ? null : tdepart.trim();
    }
}