package com.ncu.mfc.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upwd
     *
     * @mbggenerated
     */
    private String upwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.utype
     *
     * @mbggenerated
     */
    private String utype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upwd
     *
     * @return the value of user.upwd
     *
     * @mbggenerated
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upwd
     *
     * @param upwd the value for user.upwd
     *
     * @mbggenerated
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.utype
     *
     * @return the value of user.utype
     *
     * @mbggenerated
     */
    public String getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.utype
     *
     * @param utype the value for user.utype
     *
     * @mbggenerated
     */
    public void setUtype(String utype) {
        this.utype = utype == null ? null : utype.trim();
    }
}